apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecraftservers.minecraft.jameslaverack.com
spec:
  group: minecraft.jameslaverack.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                versionRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                rcon:
                  type: object
                  properties:
                    port:
                      format: int16
                      type: integer
                      minimum: 1
                      maximum: 65535
                      default: 25575
                    passwordSecretRef:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                motd:
                  type: string
                  default: "A Minecraft Server"
                eula:
                  # Don't default this. It's important that the user explicitly accepts the Minecraft EULA.
                  type: string
                  enum:
                    - Agreed
                    - NotAgreed
                difficulty:
                  type: string
                  default: Normal
                  enum:
                    - Peaceful
                    - Easy
                    - Normal
                    - Hard
                gameMode:
                  type: string
                  default: Survival
                  enum:
                    - Survival
                    - Creative
                    - Spectator
                    - Adventure
                viewDistance:
                  type: integer
                  default: 10
                  minimum: 3
                  maximum: 32
                worldSize:
                  x-kubernetes-int-or-string: true
                  default: Maximum
                  maximum: 29999984
                  minimum: 1
                  pattern: '(\d+|Maximum)'
                maximumBuildHeight:
                  type: integer
                  format: int32
                  default: 256
                  minimum: 1
                maximumPlayers:
                  type: integer
                  format: int32
                  default: 20
                  minimum: 1
                pvp:
                  type: string
                  default: PvPAllowed
                  enum:
                    - PvPAllowed
                    - PvEOnly
                worldGeneration:
                  type: object
                  properties:
                    seed:
                      type: string
                    levelType:
                      type: string
                      default: Default
                      enum:
                        - Default
                        - Flat
                        - LargeBiomes
                        - Amplified
                whitelist:
                  type: string
                  default: Disabled
                  enum:
                    - Disabled
                    - Unmanaged
                    - Managed
                spawning:
                  type: object
                  default: {}
                  properties:
                    animals:
                      type: string
                      default: Enabled
                      enum:
                        - Enabled
                        - Disabled
                    monsters:
                      type: string
                      default: Enabled
                      enum:
                        - Enabled
                        - Disabled
                    nonPlayerCharacters:
                      type: string
                      default: Enabled
                      enum:
                        - Enabled
                        - Disabled
  scope: Namespaced
  names:
    plural: minecraftservers
    singular: minecraftserver
    kind: MinecraftServer
    shortNames:
      - ms
