apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecraftserverversions.minecraft.jameslaverack.com
spec:
  group: minecraft.jameslaverack.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vanilla:
                  type: object
                  properties:
                    minecraftVersion:
                      type: string
                  required:
                    - minecraftVersion
                spigot:
                  type: object
                  properties:
                    minecraftVersion:
                      type: string
                    spigotBuild:
                      type: string
                  required:
                    - minecraftVersion
                    - spigotBuild
              oneOf:
                - required:
                  - vanilla
                - required:
                  - spigot
  scope: Namespaced
  names:
    plural: minecraftserverversions
    singular: minecraftserverversion
    kind: MinecraftServerVersion
