name: Publish Container Images
on: [push]
jobs:
  management-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sea-lantern/management-api
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
        registry: quay.io
        dockerfile: package/management-api.Dockerfile
